### ISSUE TITLE
how to work with openfire

### ISSUE THREAD

**Issue by lancelothuxi** [xmppo/node-xmpp-bosh#105]
Hello, I have little problem with my setting, Maybe I missed something, but really appreciate your help

[root@AY14040714453496619fZ node-xmpp-bosh]# node run-server.js --config=bosh.js.conf
| Starting BOSH server 'v0.7.10' on 'http://localhost:5280/^\/http-bind(\/+)?$/' at 'Tue Apr 08 2014 20:45:12 GMT+0800 (CST)' |

| Starting WEBSOCKET server 'v0.7.10' on ws://localhost:5280' at 'Tue Apr 08 2014 20:45:12 GMT+0800 (CST)' |

this seems wrong because in the installation guid,it tells to type 'bosh-server', but in my case, 'bosh-server' is not a command.. and the 5280 port is conflicting with openfire http-bind port.. Possiblely I missed some steps..thanks

**Comment by dhruvbird** [comment]
@lancelothuxi This seems okay - you probably want to change the config file to run on a different port if some other service is already running on the same port. The command bosh-server is just a short hand to do the same thing as 'node run-server.js'.

**Comment by lancelothuxi** [comment]
hello, thanks for your quick reply, still something confused... if I start NXB and set the port to 5280, should I disable openfire's built in BOSH(port is also 5280)?,  I have tried to test it by below:

GET http://mydomain:5280/http-bind/?xml=%3Cbody+content%3D%27text%2Fxml%…se%27+xmpp%3Aversion%3D%271.0%27%2F%3E&callback=**gwt_jsonp**.I0.onSuccess net::ERR_CONNECTION_REFUSED 

seems not working, openfire seems didn't receive any request, thanks for your time

**Comment by lancelothuxi** [comment]
Hello, I have another issue with me now, when for my web client IM, if I continue to refresh website,
then I will get a empty response, the log is:
FO] [session.js:Object.Session.send_invalid_packet_terminate_response:581] - 275f20c7-0f64-45c7-9a12-44b65195608a send_invalid_packet_terminate_response -- will terminate, for the config file, I just changed the domain and port
