### ISSUE TITLE
should I disable openfire built in BOSH?

### ISSUE THREAD

**Issue by lancelothuxi** [xmppo/node-xmpp-bosh#106]
hello, thanks for your quick reply for question I asked before,but  still something confused... if I start NXB and set the port to 5280, should I disable openfire's built in BOSH(port is also 5280)?, I have tried to test it by below:

GET http://mydomain:5280/http-bind/?xml=%3Cbody+content%3D%27text%2Fxml%…se%27+xmpp%3Aversion%3D%271.0%27%2F%3E&callback=gwt_jsonp.I0.onSuccess net::ERR_CONNECTION_REFUSED

seems not working, openfire seems didn't receive any request, thanks for your time

**Comment by dhruvbird** [comment]
> hello, thanks for your quick reply for question I asked before,but still something confused... if I start NXB and set the port to 5280, should I disable openfire's built in BOSH(port is also 5280)?

Yes! You can't have 2 services listening on the same host:port (endpoint) on the same machine.

You probably need to quote your URL. Have you tried running the unit/functional tests to verify if the setup is okay? (npm test).

**Comment by lancelothuxi** [comment]
thanks for your response, I then disabled openfire built in bosh listen port(7070), it is working now! thank you very much! By the way, NXB seems can automatically detect xmpp server, and work together with it wonderfully, it is really amazing

**Comment by lancelothuxi** [comment]
Hello, I have another issue with me now, when for my web client IM, if I continue to refresh website,
then I will get a empty response, the log is:
FO] [session.js:Object.Session.send_invalid_packet_terminate_response:581] - 275f20c7-0f64-45c7-9a12-44b65195608a send_invalid_packet_terminate_response -- will terminate, for the config file, I just changed the domain and port
