### ISSUE TITLE
--config not working

### ISSUE THREAD

**Issue by derekslenk** [xmppo/node-xmpp-bosh#11]
Whenever I try to set a config, because I want to change the libpurple setting, I get 

oot@epimetheus:~/.nvm/v0.4.7/lib# node node_modules/node-xmpp-bosh/run-server.js --config 'bosh.js.conf'  Caught Exception: 'Error: Cannot find module './true'' while trying to read config file './true'

I have tried it with basically every different string combination

**Comment by dhruvbird** [comment]
Hi Derek! You need to pass the option in as: --config=bosh.js.conf OR --config='bosh.js.conf'

Let me know if it still doesn't work for you.

**Comment by derekslenk** [comment]
With that file being in your node_modules/node-xmpp-bosh/ folder?

**Comment by dhruvbird** [comment]
Yes, the file should be in some folder that is in node's modules lookup path OR you can pass it an absolute path.

**Comment by derekslenk** [comment]
That worked, thank you much :)

Hopefully setting the config will help me connect using TLS...

**Comment by dhruvbird** [comment]
(y)
