### ISSUE TITLE
Can node-xmpp-bosh connect to xmpp servers with TLS ?

### ISSUE THREAD

**Issue by Trim** [xmppo/node-xmpp-bosh#118]
Hello,

I've read comments on issue #55 and PR #97 and I understand your arguments to use another service to proxy https. I've also read the BOSH xep and particulary [the security chapter](http://www.xmpp.org/extensions/xep-0124.html#security).

So the https proxy will work for connections between Client and BOSH and I'm wondering if node-xmpp-bosh will use also a secured connection to communicate with external XMPP servers (if they have one) ?

I'm interested into this feature, because I'm planning to open my BOSH server to anyone needing one.

Regards,
Adrien

**Comment by Trim** [comment]
Oh, I've just found the issue #12. Does it imply that if TLS connection for a server is available it will be used ?

**Comment by dhruvbird** [comment]
@Trim  Yes, the bosh proxy can connect securely to an existing xmpp server.
