### ISSUE TITLE
Cannot connect to TLS server

### ISSUE THREAD

**Issue by derekslenk** [xmppo/node-xmpp-bosh#12]
I am trying to connect to a TLS server on port 5223, using old style ssl.

xDexter87@pvp.net

Connect Server: chat.na1.lol.riotgames.com

I don't know if this is an issue or not, but it always says bosh terminated the connection

**Comment by dhruvbird** [comment]
Sorry, old style TLS is not supported - in fact iirc, it has been deprecated by the xmpp standard.
