### ISSUE TITLE
<stream:stream> root elements closed

### ISSUE THREAD

**Issue by astro** [xmppo/node-xmpp-bosh#14]
node-xmpp-bosh parses and sends only `<stream:stream>` elements that are closed.

[Jack Moffitt's draft](http://tools.ietf.org/html/draft-moffitt-xmpp-over-websocket-00#section-3.3) however specifies:

> The stream tag MUST NOT be closed (i.e. the closing `</stream:stream>` tag should not appear in the message) as it is the start of the client's outgoing XML.

You may need to apply some weird string magic if you insist on DOM parsing.

**Comment by dhruvbird** [comment]
You are right - we've moved to SAX based parsing for BOSH - need to do the same for websocket as well.

**Comment by dhruvbird** [comment]
@astro Does this commit https://github.com/dhruvbird/node-xmpp-bosh/commit/7b7ccfe27aec1b8f4255d1c51ada7fd5af4431de solve your problem? I haven't been able to test with a client that doesn't close the stream:stream tag since I am testing using superfeedr's strophejs mod.

**Comment by astro** [comment]
Awesome response time. I will give a try!

**Comment by astro** [comment]
It now accepts a non-closed `<stream:stream>` from my client. In response to that however node-xmpp-bosh itself sends:

```
<stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xml:lang="en" from="example.com"/>
```

**Comment by dhruvbird** [comment]
Let me know if current head works now.

**Comment by astro** [comment]
Perfect! Thank you very much.
