### ISSUE TITLE
jsjac doesn't work

### ISSUE THREAD

**Issue by vinnitu** [xmppo/node-xmpp-bosh#15]
something wrong with jsjac or node-xmpp-bosh

I try

strophe - node-xmpp-bosh - it works
jsjack - (http://bosh.metajack.im:5280/xmpp-httpbind) - it works
jsjack - node-xmpp-bosh - doesn't work

**Comment by dhruvbird** [comment]
Do you have some sort of test case that can replicate this behaviour since Jappix uses JsJac and it seems to work fine there?
Check the URLs and ports.

**Comment by vinnitu** [comment]
it works with latest version from git (thanks Stefan Strigler)

**Comment by dhruvbird** [comment]
okay - but I am a bit confused - latest version of what from git (jsjac or node-xmpp-bosh)?

**Comment by astro** [comment]
Stefan Strigler is the JSJaC author. The [repository](https://github.com/sstrigler/JSJaC/commits/master) hasn't seen changes in the past 9 days.

**Comment by vinnitu** [comment]
Yes ) He is author and he points to git version (not release 1.3.4).

**Comment by dhruvbird** [comment]
ah! I see now. Release 1.3.4 was almost a year ago!
