### ISSUE TITLE
npm install node-xmpp-bosh

### ISSUE THREAD

**Issue by vinnitu** [xmppo/node-xmpp-bosh#19]
I received  warning:

> contextify@0.1.2 install /home/sklyar/node_modules/node-xmpp-bosh/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module '/usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
npm WARN optional dependency failed, continuing contextify@0.1.2

Is it problem?

**Comment by dhruvbird** [comment]
jsdom is needed only for running tests. You should be okay even without it.
