### ISSUE TITLE
<?xml version='1.0'?>

### ISSUE THREAD

**Issue by vinnitu** [xmppo/node-xmpp-bosh#26]
One of php jabber-client use SimpleXML class to build xmpp stanza and SimpleXMLElement::asXML() function to get result string, but always return preambula &lt;?xml version='1.0'?&gt; at begin

and in node-xmpp-bosh next construction not working properly

&lt;dummy&gt;&lt;?xml version='1.0'?&gt;&lt;bla&gt;bla&lt;/bla&gt;&lt;/dummy&gt;

because dummy is not valid xml element, and that is why developers make dirty hack with 

s = substr(s, strlen('&lt;?xml version='1.0'?&gt;');

but ejabberd_http_bind hasn't such trouble

So... What do you think about?

**Comment by dhruvbird** [comment]
The line "<?xml version='1.0'?>" should probably be present only when a xml doc. starts. I could be wrong though.

**Comment by vinnitu** [comment]
what is main idea usign dummy wrapper?

**Comment by dhruvbird** [comment]
to prevent xml entity expansion attack.

**Comment by dhruvbird** [comment]
Even if we switch to a sax parser for the websocket bit, the xml you paste will be invalid since we just keep continuing the same xml document - which can't have <? xml ... ?> in the middle.
