### ISSUE TITLE
Missing terminate when resource conflict occurs

### ISSUE THREAD

**Issue by lboynton** [xmppo/node-xmpp-bosh#29]
I noticed that when there is a resource conflict, node-xmpp-bosh doesn't include a type="terminate" on the body element.

```
<body xmlns="http://jabber.org/protocol/httpbind" stream="0d45874e-5fd1-4cdc-a4b7-f94d4f0ca763">
<stream:error xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0">
<conflict xmlns="urn:ietf:params:xml:ns:xmpp-streams"/>
<text xml:lang="" xmlns="urn:ietf:params:xml:ns:xmpp-streams">Replaced by new connection</text>
</stream:error>
</body>
```

When testing against ejabberd, it does include type="terminate", and I think this is the correct behaviour after looking at http://xmpp.org/extensions/xep-0206.html#remote-stream-error

**Comment by lboynton** [comment]
I've just noticed this has been fixed in a newer version to the one I'm using!

**Comment by dhruvbird** [comment]
yes, issue #21
