### ISSUE TITLE
[not a bug] How to extend node-xmpp-bosh

### ISSUE THREAD

**Issue by maxguzenski** [xmppo/node-xmpp-bosh#31]
Hi,
Is there a way to send a notification to clients without going through my xmpp server? that is, use it as a normal channel service like fayer or socket.io

Explaining:  I have a webchat that use prosody with node-xmpp-bosh, but I'd like to send notifications (from main server) to users like "your photo  received a new comment". I know that I could use prosody for this, but maybe it is more simple just use node-xmpp-bosh.

is it possible?

**Comment by dhruvbird** [comment]
Others also seem to want this functionality. See: http://stackoverflow.com/questions/10459776/xmpp-push-notification-for-ios-chat-app/10578003

We might create set of helpers to make this easier in the future.
