### ISSUE TITLE
How to use it with pidgin/adium?

### ISSUE THREAD

**Issue by anildigital** [xmppo/node-xmpp-bosh#35]
I want to login to my gtalk.. by using pidgin/adium?

How to I make use of https://bind.jappix.com/ ?

![adium setting](https://www.evernote.com/shard/s8/sh/54b5692e-02ae-4078-a7e2-8d8f25aab0d6/c97a9bedb5fd7beb19667396c1ac6543/res/fb52a6d7-01df-45e6-96e2-6c7013c3dfdb/Adium-20120614-232000.png.jpg)

**Comment by dhruvbird** [comment]
Keep "connect server" empty. Set "BOSH Server" to "https://jappix.com/bind"
Uncheck "Do strict certificate checks" - though I think jappix has a valid cert.
Let me know if it works.

Forgot to mention. This won't work unless the jappix admins have set "pidgin_compatible" to "true" in their configuration.

**Comment by dhruvbird** [comment]
@anildigital Does this answer your question?

**Comment by anildigital** [comment]
Nope. I can't use https. With http it stays till 25%.

**Comment by dhruvbird** [comment]
@anildigital Sorry, but I seem to have misunderstood. I thought your original question was about using nxb with pidgin?

**Comment by dhruvbird** [comment]
Closing. Too old. Please re-open if something turns up.
