### ISSUE TITLE
Running node-xmpp-bosh on nodejitsu

### ISSUE THREAD

**Issue by immanuel** [xmppo/node-xmpp-bosh#36]
I'm trying to run node-xmpp-bosh on nodejitsu. After deploying it to nodejitsu I see the "Starting BOSH server" and "Starting WEBSOCKET server" messages on the log file. But the server doesn't seem to be running - http-bind/ gives a broken link. 

The deployed app starts with run-server.js. Is this the correct way to start the BOSH server? 

is there any other way I can run node-xmpp-bosh on a public server - I want to test it out on a free service like nodejitsu or CloudFoundry.

**Comment by dhruvbird** [comment]
What you are doing seems to be right. The server should start, print out the message and just appear to "hang". If you are trying to connect from an external machine, you might want to check your firewall or check your ports. Either ways, the best way would be to first connect from the local machine (on which you are running the server).

$ curl http://localhost:PORT/http-bind/ # This should print some HTML
$ echo $? # Should print 0

Also, you might want to run in --logging=TRACE level and check your error logs for any crashes.

**Comment by immanuel** [comment]
You are right. It does work! The HTTP GET support showed the result as described in the docs. 

Thanks for the prompt reply! 

Now to the strophe part!
