### ISSUE TITLE
Bug: node-xmpp-bosh not starting.

### ISSUE THREAD

**Issue by gshergill** [xmppo/node-xmpp-bosh#39]
Hi.

When I run the command to start the bosh server, I receive the following:

root@jappix:~# /etc/init.d/bosh restart
Restarting bosh serverStopping bosh server.
Starting bosh server.
.
root@jappix:~# node: no process found

Checking the error log, I find the following error:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'consoleAppender'
    at Object.<anonymous> (/usr/local/lib/node_modules/node-xmpp-bosh/src/log.js:7:23)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-xmpp-bosh/src/dutil.js:534:30)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)

Been checking for a fix for some time now, any help would be appreciated.

Thanks.

**Comment by dhruvbird** [comment]
Check https://github.com/dhruvbird/node-xmpp-bosh/issues/33 for a fix

**Comment by dhruvbird** [comment]
I forgot to mention - after changing the dependency, from the directory where you have the _node_modules_ directory (or the _package.json_ file) , type:

```
$> npm install .
```

This command will fetch the right version for log4js.

**Comment by gshergill** [comment]
Hi, thanks for the quick reply.

I tried that before and I have about 30 different files called package.json.

/home/localadm/.npm/abbrev/1.0.3/package/package.json
/home/localadm/.npm/ansi/0.1.2/package/package.json
/home/localadm/.npm/async/0.1.15/package/package.json
/home/localadm/.npm/block-stream/0.0.6/package/package.json
/home/localadm/.npm/colors/0.6.0-1/package/package.json
/home/localadm/.npm/dns-srv/0.0.6/package/package.json
/home/localadm/.npm/dns-srv/0.0.6/package/package.json~
/home/localadm/.npm/eventpipe/0.0.3/package/package.json
/home/localadm/.npm/fstream/0.1.18/package/package.json
/home/localadm/.npm/glob/3.1.10/package/package.json
/home/localadm/.npm/graceful-fs/1.1.8/package/package.json
/home/localadm/.npm/http-proxy/0.8.1/package/package.json
/home/localadm/.npm/http-proxy/0.8.1/package/examples/package.json
/home/localadm/.npm/inherits/1.0.0/package/package.json
/home/localadm/.npm/log4js/0.5.0/package/package.json
/home/localadm/.npm/lru-cache/1.1.0/package/package.json
/home/localadm/.npm/ltx/0.2.1/package/package.json
/home/localadm/.npm/minimatch/0.2.5/package/package.json
/home/localadm/.npm/mkdirp/0.3.3/package/package.json
/home/localadm/.npm/node-expat/1.6.0/package/package.json
/home/localadm/.npm/node-gyp/0.5.6/package/package.json
/home/localadm/.npm/node-uuid/1.3.3/package/package.json
/home/localadm/.npm/node-xmpp-bosh/0.6.1/package/package.json
/home/localadm/.npm/nopt/1.0.10/package/package.json
/home/localadm/.npm/npmlog/0.0.2/package/package.json
/home/localadm/.npm/optimist/0.2.8/package/package.json
/home/localadm/.npm/pkginfo/0.2.3/package/package.json
/home/localadm/.npm/pkginfo/0.2.3/package/examples/package.json
/home/localadm/.npm/request/2.9.203/package/package.json
/home/localadm/.npm/rimraf/2.0.2/package/package.json
/home/localadm/.npm/sax/0.4.0/package/package.json
/home/localadm/.npm/semver/1.0.14/package/package.json
/home/localadm/.npm/tar/0.1.13/package/package.json
/home/localadm/.npm/tav/0.1.0/package/package.json
/home/localadm/.npm/underscore/1.3.3/package/package.json
/home/localadm/.npm/websocket/1.0.5/package/package.json
/home/localadm/.npm/websocket/1.0.5/package/example/whiteboard/node_modules/ejs/package.json
/home/localadm/.npm/websocket/1.0.5/package/example/whiteboard/node_modules/ejs/support/expresso/package.json
/home/localadm/.npm/websocket/1.0.5/package/example/whiteboard/node_modules/express/package.json
/home/localadm/.npm/websocket/1.0.5/package/example/whiteboard/node_modules/express/testing/foo/package.json
/home/localadm/.npm/which/1.0.5/package/package.json
/home/localadm/.npm/wordwrap/0.0.2/package/package.json
/home/localadm/node_modules/http-proxy/package.json
/home/localadm/node_modules/http-proxy/examples/package.json
/home/localadm/node_modules/http-proxy/node_modules/colors/package.json
/home/localadm/node_modules/http-proxy/node_modules/optimist/package.json
/home/localadm/node_modules/http-proxy/node_modules/optimist/node_modules/wordwrap/package.json
/home/localadm/node_modules/http-proxy/node_modules/pkginfo/package.json
/home/localadm/node_modules/http-proxy/node_modules/pkginfo/examples/package.json
/home/localadm/node_modules/node-gyp/package.json
/home/localadm/node_modules/node-gyp/node_modules/fstream/package.json
/home/localadm/node_modules/node-gyp/node_modules/fstream/node_modules/inherits/package.json
/home/localadm/node_modules/node-gyp/node_modules/glob/package.json
/home/localadm/node_modules/node-gyp/node_modules/glob/node_modules/inherits/package.json
/home/localadm/node_modules/node-gyp/node_modules/graceful-fs/package.json
/home/localadm/node_modules/node-gyp/node_modules/minimatch/package.json
/home/localadm/node_modules/node-gyp/node_modules/minimatch/node_modules/lru-cache/package.json
/home/localadm/node_modules/node-gyp/node_modules/mkdirp/package.json
/home/localadm/node_modules/node-gyp/node_modules/nopt/package.json
/home/localadm/node_modules/node-gyp/node_modules/nopt/node_modules/abbrev/package.json
/home/localadm/node_modules/node-gyp/node_modules/npmlog/package.json
/home/localadm/node_modules/node-gyp/node_modules/npmlog/node_modules/ansi/package.json
/home/localadm/node_modules/node-gyp/node_modules/request/package.json
/home/localadm/node_modules/node-gyp/node_modules/rimraf/package.json
/home/localadm/node_modules/node-gyp/node_modules/semver/package.json
/home/localadm/node_modules/node-gyp/node_modules/tar/package.json
/home/localadm/node_modules/node-gyp/node_modules/tar/node_modules/block-stream/package.json
/home/localadm/node_modules/node-gyp/node_modules/tar/node_modules/inherits/package.json
/home/localadm/node_modules/node-gyp/node_modules/which/package.json
]/usr/local/lib/node_modules/node-gyp/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/fstream/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/fstream/node_modules/inherits/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/glob/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/glob/node_modules/inherits/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/graceful-fs/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/minimatch/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/minimatch/node_modules/lru-cache/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/mkdirp/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/nopt/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/nopt/node_modules/abbrev/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/npmlog/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/npmlog/node_modules/ansi/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/request/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/rimraf/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/semver/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/tar/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/tar/node_modules/block-stream/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/tar/node_modules/inherits/package.json
/usr/local/lib/node_modules/node-gyp/node_modules/which/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/dns-srv/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/dns-srv/package.json~
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/eventpipe/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/log4js/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/log4js/node_modules/async/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/ltx/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/ltx/node_modules/sax/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/node-expat/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/node-uuid/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/semver/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/tav/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/underscore/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/websocket/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/websocket/example/whiteboard/node_modules/ejs/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/websocket/example/whiteboard/node_modules/ejs/support/expresso/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/websocket/example/whiteboard/node_modules/express/package.json
/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/websocket/example/whiteboard/node_modules/express/testing/foo/package.json
/usr/share/doc/node-fstream/examples/deep-copy/package.json
/usr/share/npm/package.json
/usr/share/npm/node_modules/proto-list/package.json
/usr/share/npm/node_modules/read/package.json
/usr/share/npm/node_modules/slide/package.json

**Comment by dhruvbird** [comment]
This one _/usr/local/lib/node_modules/node-xmpp-bosh/package.json_, so you need to be in the directory _/usr/local/lib/node_modules/node-xmpp-bosh_ before running _npm install ._. The package that will be reinstalled by npm is the one at _/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/log4js/_.

Sorry for the trouble. We should have checked the dependencies strictly.

**Comment by gshergill** [comment]
Ok I did the following:

vi /usr/local/lib/node_modules/node-xmpp-bosh/package.json
   removes the ">" sign

cd /usr/local/lib/node_modules/node-xmpp-bosh
npm install .

npm ERR! Couldn't read dependencies.

npm ERR! Error: ENOENT, no such file or directory '/home/localadm/package.json'
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/localadm/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "node" "/usr/bin/npm" "install" "."
npm ERR! cwd /home/localadm
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! path /home/localadm/package.json
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/home/localadm/package.json'
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/localadm/npm-debug.log
npm not ok
root@jappix:~# /usr/local/lib/node_modules/node-xmpp-bosh/package.json
bash: /usr/local/lib/node_modules/node-xmpp-bosh/package.json: Permission denied
root@jappix:~# vi /usr/local/lib/node_modules/node-xmpp-bosh/package.json
root@jappix:~# 
root@jappix:~# 
root@jappix:~# cd /usr/local/lib/node_modules/node-xmpp-bosh
root@jappix:/usr/local/lib/node_modules/node-xmpp-bosh# npm install .
npm WARN node-xmpp-bosh@0.6.1 package.json: bugs['name'] should probably be bugs['url']
npm WARN ltx@0.2.1 package.json: bugs['name'] should probably be bugs['url']
npm WARN eventpipe@0.0.3 package.json: bugs['name'] should probably be bugs['url']
npm WARN node-expat@1.6.0 package.json: bugs['name'] should probably be bugs['url']
npm http GET https://registry.npmjs.org/log4js/0.4.2
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/jslint
npm http 200 https://registry.npmjs.org/log4js/0.4.2
npm http GET https://registry.npmjs.org/log4js/-/log4js-0.4.2.tgz
npm http 200 https://registry.npmjs.org/jslint
npm http GET https://registry.npmjs.org/jslint/-/jslint-0.1.8.tgz
npm http 200 https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/jsdom/-/jsdom-0.2.14.tgz
npm http 200 https://registry.npmjs.org/log4js/-/log4js-0.4.2.tgz
npm http 200 https://registry.npmjs.org/jsdom/-/jsdom-0.2.14.tgz
npm http 200 https://registry.npmjs.org/jslint/-/jslint-0.1.8.tgz
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/async/0.1.15
npm http GET https://registry.npmjs.org/compress-buffer
npm http GET https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/abbrev
npm http 200 https://registry.npmjs.org/async/0.1.15
npm http GET https://registry.npmjs.org/async/-/async-0.1.15.tgz
npm http 200 https://registry.npmjs.org/compress-buffer
npm http GET https://registry.npmjs.org/compress-buffer/-/compress-buffer-1.1.0.tgz
npm http 200 https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssom/-/cssom-0.2.4.tgz
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/async/-/async-0.1.15.tgz
npm http 200 https://registry.npmjs.org/compress-buffer/-/compress-buffer-1.1.0.tgz
npm http 200 https://registry.npmjs.org/cssom/-/cssom-0.2.4.tgz
npm http 200 https://registry.npmjs.org/contextify
npm http 200 https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/contextify/-/contextify-0.1.3.tgz
npm http GET https://registry.npmjs.org/htmlparser/-/htmlparser-1.7.6.tgz

> compress-buffer@1.1.0 install /usr/local/lib/node_modules/node-xmpp-bosh/node_modules/log4js/node_modules/compress-buffer
> make build

rm -Rf build
node-waf configure
Checking for program g++ or c++          : /usr/bin/g++ 
npm http 200 https://registry.npmjs.org/htmlparser/-/htmlparser-1.7.6.tgz
npm http 200 https://registry.npmjs.org/contextify/-/contextify-0.1.3.tgz
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
'configure' finished successfully (0.371s)
node-waf build
Waf: Entering directory `/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/log4js/node_modules/compress-buffer/build'
[1/2] cxx: src/compress-buffer.cc -> build/Release/src/compress-buffer_1.o
[2/2] cxx_link: build/Release/src/compress-buffer_1.o -> build/Release/compress-buffer-bindings.node
Waf: Leaving directory`/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/log4js/node_modules/compress-buffer/build'
'build' finished successfully (1.078s)
npm WARN htmlparser@1.6.2 package.json: bugs['web'] should probably be bugs['url']

> contextify@0.1.3 preinstall /usr/local/lib/node_modules/node-xmpp-bosh/node_modules/jsdom/node_modules/contextify
> node-waf clean || (exit 0); node-waf configure build

Nothing to clean (project not configured)
Setting srcdir to                        : /usr/local/lib/node_modules/node-xmpp-bosh/node_modules/jsdom/node_modules/contextify 
Setting blddir to                        : /usr/local/lib/node_modules/node-xmpp-bosh/node_modules/jsdom/node_modules/contextify/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
'configure' finished successfully (0.075s)
Waf: Entering directory `/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/jsdom/node_modules/contextify/build'
[1/2] cxx: src/contextify.cc -> build/Release/src/contextify_1.o
[2/2] cxx_link: build/Release/src/contextify_1.o -> build/Release/contextify.node
Waf: Leaving directory`/usr/local/lib/node_modules/node-xmpp-bosh/node_modules/jsdom/node_modules/contextify/build'
'build' finished successfully (0.623s)
npm http GET https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz
npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz
jslint@0.1.8 ./node_modules/jslint 
└── nopt@1.0.10
log4js@0.4.2 ./node_modules/log4js 
├── async@0.1.15
└── compress-buffer@1.1.0
jsdom@0.2.14 ./node_modules/jsdom 
├── cssom@0.2.4
├── request@2.9.203
├── htmlparser@1.7.6
└── contextify@0.1.3

/etc/init.d/bosh restart

This seems to have worked fine, Thanks a lot =)

The original reason for my doing this was because my Jappix wasn't running properly (service unavailable error) and I realised that the bosh wasn't actually running.

Now when I try to log in to Jappix it seems to be "trying" to log on (whereas before it didn't even try) but still comes up with the same error of Service Unavailable.

This is in the bosh.log (bosh.err is empty ^^):

+-------------------------------------------------------------------------------------------------------+
| Starting WEBSOCKET server 'v0.6.1' on ws://0.0.0.0:5280' at 'Wed Jul 04 2012 16:28:25 GMT+0100 (BST)' |
+-------------------------------------------------------------------------------------------------------+

I am unsure as to whether this is an issue which I can ask you about.

On a related note, how can I confirm that my Openfire server is using node-xmpp-bosh rather than it's own?

Thanks again, I really appreciate the help.

**Comment by gshergill** [comment]
My apologies, the following is in the bosh.log (and it appears when the bosh is restarted):

+--------------------------------------------------------------------------------------------------------------------------+
| Starting BOSH server 'v0.6.1' on 'http://0.0.0.0:5280/^\/http-bind(\/+)?$/' at 'Wed Jul 04 2012 16:35:01 GMT+0100 (BST)' |
+--------------------------------------------------------------------------------------------------------------------------+
+-------------------------------------------------------------------------------------------------------+
| Starting WEBSOCKET server 'v0.6.1' on ws://0.0.0.0:5280' at 'Wed Jul 04 2012 16:35:01 GMT+0100 (BST)' |
+-------------------------------------------------------------------------------------------------------+

**Comment by gshergill** [comment]
In regards to node-xmpp-bosh, it randomly stops working and the following appears in bosh.err:

events.js:48
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: 140050427569984:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:724:

```
at CleartextStream._puller (tls.js:501:24)
at CleartextStream._pull (tls.js:432:19)
at SecurePair.cycle (tls.js:727:20)
at EncryptedStream.write (tls.js:130:13)
at Socket.ondata (stream.js:38:26)
at Socket.emit (events.js:67:17)
at TCP.onread (net.js:347:14)
```

Any ideas?

**Comment by dhruvbird** [comment]
Cool - glad you could get it working with Jappix.

Is there some context you could provide regarding what caused the crash, such as what site you were trying to connect to, etc.. It would also help to run in TRACE logging mode (--logging=TRACE) and post the bosh.log contents.

**Comment by gshergill** [comment]
Thanks dhruv.

At the moment the error has stopped - am not sure why it randomly crashed (I was trying to log on the Jappix web client).

Since my last post I have been trying to search through the bosh files to find where to configure the bosh to point to Openfire, there are a plethora of files to look through (most of which are >300 lines in vi).

Would you be able to point me in the right direction please? Not even sure what I am looking for to be honest...

Thanks again, you have been great with the help

**Comment by dhruvbird** [comment]
You don't need any BOSH config to achieve this. Just connect to the right server from your bosh client, and the bosh server will try to connect to the server hosted on that host:port.

**Comment by gshergill** [comment]
Thanks, it's all working =)

(sorry on the late reply)
