### ISSUE TITLE
JSON GET feature is broken

### ISSUE THREAD

**Issue by valeriansaliou** [xmppo/node-xmpp-bosh#51]
Hello,

After upgrading from 0.3.1 to the latest 0.6.1 I noticed the JSON GET handler was broken, the browser says that a variable has no end as an error.

Some Jappix users, using NXB as we recommend them, were posting about that in our issues, at first thought it was coming from us, but I tried myself to upgrade node-xmpp-bosh and noticed that also.

Cheers ;)

**Comment by valeriansaliou** [comment]
Seems to be more like a node issue, using node v0.8.8, get this error when using JSON GET handler:

root@iflo:/usr/local/lib/bosh# node ./run-server.js 
+----------------------------------------------------------------------------------------------------------------------+
| Starting BOSH server 'v0.3.1' on 'http://:::5280/^\/http-bind(\/+)?$/' at 'Tue Aug 28 2012 22:28:37 GMT+0200 (SAST)' |
+----------------------------------------------------------------------------------------------------------------------+

/usr/local/lib/bosh/src/bosh.js:659
        res.socket.setTimeout(state.wait \* 1000 + 10);
                   ^
TypeError: Cannot call method 'setTimeout' of undefined
    at add_held_http_connection (/usr/local/lib/bosh/src/bosh.js:659:20)
    at new_state_object (/usr/local/lib/bosh/src/bosh.js:424:3)
    at session_create (/usr/local/lib/bosh/src/bosh.js:467:15)
    at process_bosh_request (/usr/local/lib/bosh/src/bosh.js:1315:13)
    at bosh_requst_handler (/usr/local/lib/bosh/src/bosh.js:1692:3)
    at handle_get_bosh_request (/usr/local/lib/bosh/src/bosh.js:1732:4)
    at Object.EventPipe.emit (/usr/local/lib/bosh/node_modules/eventpipe/eventpipe.js:63:25)
    at Server.http_request_handler (/usr/local/lib/bosh/src/bosh.js:1834:10)
    at Server.EventEmitter.emit (events.js:91:17)
    at HTTPParser.parser.onIncoming (http.js:1793:12)

**Comment by valeriansaliou** [comment]
Using node v0.8.8 + NXB latest from Git, this error:

/usr/local/lib/bosh/src/http-server.js:66
            if (!bosh_request_parser.parse(u.query.data)) {
                                     ^
TypeError: Cannot call method 'parse' of null
    at Object.handle_get_bosh_request [as proc](/usr/local/lib/bosh/src/http-server.js:66:38)
    at Object.EventPipe.emit (/usr/local/lib/bosh/node_modules/eventpipe/eventpipe.js:74:31)
    at Server.http_request_handler (/usr/local/lib/bosh/src/http-server.js:224:16)
    at Server.EventEmitter.emit (events.js:91:17)
    at HTTPParser.parser.onIncoming (http.js:1793:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:111:23)
    at Socket.socket.ondata (http.js:1690:22)
    at TCP.onread (net.js:402:27)
root@iflo:/usr/local/lib/bosh#

**Comment by dhruvbird** [comment]
@vanaryon Can you check current master to see if this is fixed? Commit id 51c62f7666169a1f7e0e583ba724ba8825b459bf

**Comment by valeriansaliou** [comment]
Same error user side, chain constant not ended. But on NXB side it does not crash anymore now, no log about a session intiated at all.

**Comment by dhruvbird** [comment]
@vanaryon That error usually means that you have something else already running on that port. Try netstat -l to see if that port is available.

**Comment by valeriansaliou** [comment]
Yes, noticed that, I removed my comment about that, you received it before I see ;) Anyway, I could start NXB but it still does not work client-side. Server-side, no more crash nor log.

**Comment by dhruvbird** [comment]
@vanaryon That is strange - I tested using this command:

```
$ curl "http://localhost:5280/http-bind/" -G --data-urlencode "data=<body><blah/></body>"
```

and this is what I get:

```
<body xmlns="http://jabber.org/protocol/httpbind" condition="item-not-found" message="Invalid session ID" type="terminate"/>
```

**Comment by valeriansaliou** [comment]
I see, strange! Anyway there was something broken, but my setup still does not work.

This is the BOSH server listening: http://iflo.dedicated.co.za/bind (updated with your commit). I'll proceed further tests. What is strange is that Jappix Mini works on IE using the GET method with the outdated NXB on Jappix.com, but not with the latest one. I'll investigate now and keep you updated.

**Comment by dhruvbird** [comment]
Try this request:

```
$ curl "http://iflo.dedicated.co.za/bind" -G --data-urlencode "data=<body><blah/></body>"
```

gives this response:

```
<body xmlns="http://jabber.org/protocol/httpbind" condition="item-not-found" message="Invalid session ID" type="terminate"/>
```

**Comment by dhruvbird** [comment]
@vanaryon Let me know if the master crashes on any of your tests since we are investigating any such issues and fixing them (post refactoring that happened in the recent releases). Is the IE7 failure a crash or a hanging request?

**Comment by valeriansaliou** [comment]
http://iflo.dedicated.co.za/bind?callback=jXHR.cb0&data=%3Cbody%20xml%3Alang%3D'en'%20content%3D'text%2Fxml%3B%20charset%3Dutf-8'%20hold%3D'1'%20xmlns%3D'http%3A%2F%2Fjabber.org%2Fprotocol%2Fhttpbind'%20to%3D'iflo.dedicated.co.za'%20wait%3D'20'%20rid%3D'195842'%20secure%3D'true'%20newkey%3D'4ae0246df4f224375273b8ac742ec196e6fe433c'%20ver%3D'1.6'%20xmlns%3Axmpp%3D'urn%3Axmpp%3Axbosh'%20xmpp%3Aversion%3D'1.0'%2F%3E

**Comment by valeriansaliou** [comment]
You've got a good example of the issue. Maybe not only in the URL parsing module but also in the JSON generation process. The chain is broke, here.

**Comment by valeriansaliou** [comment]
And the crash was noticed in IE8, but applies to NXB since the response JSON is not properly returned (missing closing tags).

**Comment by dhruvbird** [comment]
Yes, you are right. This is related to a bad content-length header which we started sending to support old browsers. Fix should be on 1a9ef4703e4dbe69e1ec99a1597f79a48f8f1093

**Comment by valeriansaliou** [comment]
Mhh the reference to the fix seems to be broken, did you commit anything?

**Comment by dhruvbird** [comment]
There probably is a pending utf-8 related fix to this commit, which I'll look at in a bit. Let me know if responses that have unicode (non ascii) characters result in a bad response.

**Comment by dhruvbird** [comment]
@vanaryon forgot to push.

**Comment by valeriansaliou** [comment]
Okay, updated, now it replies well. I don't know why it still does not work with the same error "Constant chain not terminated well".

**Comment by valeriansaliou** [comment]
Ah, I see why.

An example reply:
`jXHR.cb0({"reply":"<body xmlns=\"http://jabber.org/protocol/httpbind\" condition=\"item-not-found\" message=\"Invalid session ID\" type=\"terminate\"/>\"});`

The last " is also escaped, but it should not. That's why the var is still not terminated.

**Comment by dhruvbird** [comment]
@vanaryon Okay, I've rewritten the whole logic to use JSON.stringify and handle the utf8 characters properly. d0c1186ec0a6efabd9761321eb89d475bcdaf919

**Comment by valeriansaliou** [comment]
Thanks, seems like the JSON is correctly formatted now.

Another problem: the data parser seems not working fine, or the response manager always output the same error. When I initiate a session I always get that return:

`reply: "<body xmlns="http://jabber.org/protocol/httpbind" condition="item-not-found" message="Invalid session ID" type="terminate"/>"`

Where using POST with the same request it works fine.

**Comment by dhruvbird** [comment]
@vanaryon Commit 1b8708dededdc2cb566a7f12356ec2d2f1093f37 should fix the bad response on session creation. It was a problem with every GET request. Do you have an automated test suite that can be run to check the correctness before each commit? Even something as simple as a set of shell scripts which check the validity of responses is okay - just to ensure that things "work" after each commit.

**Comment by dhruvbird** [comment]
cd38d6a7f11386ea274422a9ae5c1824d71e554b tries to make the 'socket' property visible on the proxy response object. However, it doesn't explain why you saw the crash on 0.8.8. I'll have to see the commit for 0.3.1 and see if it is a real red flag or something that was fixed in a future version.

**Comment by valeriansaliou** [comment]
Works fine now, thanks a lot! IE can connect through GET method ;)

**Comment by dhruvbird** [comment]
@vanaryon Most welcome! btw, I've just pushed a change that avoids re-creating a parser object on error or invalid request and reset()s the existing parser. This should be both faster and less memory intensive and should result in generally less memory consumption. Going from 0.3.1 to 0.6.x should already have made all clients use the same parser object, which should help reduce memory consumption a lot. Let me know if you see reduced memory usage or see any problem with the new code.

**Comment by valeriansaliou** [comment]
Going to update this, thanks! ;)
