### ISSUE TITLE
Can't find node-expad.node module

### ISSUE THREAD

**Issue by snowmantw** [xmppo/node-xmpp-bosh#58]
I just find that `npm install` won't make it, and nxb will launch failed unless I manually build it via `node-gyp` make in `/node-modules/node-expat`. 

Not sure it's a nxb or `node-expat` issue. But I encountered it when I installed new nxb version, so I leave a record here.

---

node: v0.6.12 ( ubuntu default )
os: ubuntu 12.04.1

**Comment by dhruvbird** [comment]
Yes, this is expected since I doubt if node v0.6.12 came with node-gyp by default. npm uses the GYP at location: `$HOME/.node-gyp/0.6.17/tools/gyp_addon` - can you confirm if you have that file? Of course, for you, it would be `$HOME/.node-gyp/0.6.12/tools/gyp_addon`.

**Comment by snowmantw** [comment]
No, `~/.node-gyp/0.6.12/` not contains such file. And as you said, using v0.6.12 means you need install `node-gyp` via `npm`. I noticed this because I need build a stress testing environment, and hope the `ws` module can be built as native module.

**Comment by dhruvbird** [comment]
(y) yes - otherwise `ws` will be slower than usual. Please reopen if the issue is different from what we think it is.
