### ISSUE TITLE
How to set it up with external XMPP server (e.g. GTalk)

### ISSUE THREAD

**Issue by szimek** [xmppo/node-xmpp-bosh#60]
Is there config example how to setup nxb to act as BOSH proxy to some existing XMPP server like GTalk?

**Comment by dhruvbird** [comment]
@szimek You don't need to do anything special - just run "node run-server.js" (or the executable 'bosh') and you have a BOSH proxy to any publicly XMPP server that can be contacted from the proxy machine.
