### ISSUE TITLE
Node-xmpp-bosh with Jappix mini - Connecting users

### ISSUE THREAD

**Issue by hzzg6y** [xmppo/node-xmpp-bosh#61]
1. How to I disable the https or SSL & TLS access for NXB. I need it to be accessed over normal http instead of secured. Just want to check as it is causing problem for me while connecting.  I am getting RSA / CA certificate error & NXB is saying host unknown error. 
2. I am looking for mechanism where the user need to authenticated, then only they can connect to NXB. Can we integrate via MYSQL or node-db or Express. I mean
   any chat user should be able to connect only when he is available in MYSQL DB or Express DB. 
3. It is possible to create the Group for chat users in one room. I mean users in one group cannot connect or talk to users in other group. Only that group is
   visible. 

I am using latest NXB with Jappix Mini.

**Comment by dhruvbird** [comment]
> How to I disable the https or SSL & TLS access for NXB. I need it to be accessed over normal http instead of secured. Just want to check as it is causing problem for me while connecting. I am getting RSA / CA certificate error & NXB is saying host unknown error.

By default, NXB doesn't support HTTPS (when the client [user] is connecting to the proxy), so you don't need to disable it. TLS to communicate with the XMPP server is enabled by default and can be disabled for certain domains. See the README for more info. on this.

> I am looking for mechanism where the user need to authenticated, then only they can connect to NXB. Can we integrate via MYSQL or node-db or Express. I mean any chat user should be able to connect only when he is available in MYSQL DB or Express DB.

Use the XMPP authentication for this. Usually ejabberd/prosody let you select the backend/authentication mechanism.

> It is possible to create the Group for chat users in one room. I mean users in one group cannot connect or talk to users in other group. Only that group is visible.

This is again an XMPP server feature.
