### ISSUE TITLE
daemonize support(or document)

### ISSUE THREAD

**Issue by zh99998** [xmppo/node-xmpp-bosh#69]
as a server, it should use as a daemon.
well, i really believe there is already a daemon support in node-xmpp-bosh, but i can't find any document about it.
i've tested 

``` bash
sudo bosh-server &
```

but it stopped immediately

**Comment by dhruvbird** [comment]
It doesn't support daemonization natively, but you should be able to use daemontools which gives you much more power/features. https://code.google.com/p/node-xmpp-bosh/wiki/DaemontoolsSetup
