### ISSUE TITLE
Weird HTTP server freeze

### ISSUE THREAD

**Issue by valeriansaliou** [xmppo/node-xmpp-bosh#75]
Hello,

First, a personal note: I finally decided myself to update NXB after 2 years of awesomeness (a great uptime, no bug, only node memory leaks).

I successfully upgraded to latest node release + latest NXB release, working almost perfectly, since my NXB setup strangely locks itself after a while (generally after 45 minutes up), and https://bind.jappix.com/ only returns a blank page, no 500 error.

I checked server-side and node is still launched, but the built-in HTTP server on port 5280 refuses connections.

Note: I am using NXB on :: port, so that it's available through IPv6. Maybe the issue comes from there?

**Comment by valeriansaliou** [comment]
Due to latest node apparently, a node downgrade to latest 0.6.12 fixed the issue.

**Comment by dhruvbird** [comment]
@valeriansaliou Are you using NXB from master?
Is it a node bug?

**Comment by dhruvbird** [comment]
@valeriansaliou Thanks for the kind words :)
