### ISSUE TITLE
Accented chars and special chars in JID

### ISSUE THREAD

**Issue by valeriansaliou** [xmppo/node-xmpp-bosh#80]
Noticed a bug with accented chars in JID, as well as other kind of special chars.
It seems that the challenge string does not match.

A friend of me had a test on Prosody's internal BOSH and there's no issue there, everything is working as expected with special char usernames.

See this XML trace sent back to me from NXB as connection error:

``` xml
<body xmlns="http://jabber.org/protocol/httpbind" stream="4eae8cc9-2318-4fae-9e3b-5bdf34c85e27">
  <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl" xmlns:stream="http://etherx.jabber.org/streams" version="1.0">
    <not-authorized/>
    <text>The response provided by the client doesn't match the one we calculated.</text>
  </failure>
</body>
```

Running NXB v0.7.4 (npm)

**Comment by valeriansaliou** [comment]
Due to https://code.lightwitch.org/metronome/file/f36f1b2436bf/util/sasl/digest-md5.lua#l131
Sorry ;)

**Comment by dhruvbird** [comment]
No issues, I would have gotten to this on tuesday since am out.
Thanks for updating.

**Comment by valeriansaliou** [comment]
Ok, np.
Found out that it wasn't due to Metronome either. It's due to the JSJaC lib: https://github.com/sstrigler/JSJaC/issues/56
