### ISSUE TITLE
long polling on ios devices...

### ISSUE THREAD

**Issue by netdude787** [xmppo/node-xmpp-bosh#83]
Hi,
Is there a way to avoid long polling in node-xmpp BOSH? Something like "always-available" kind of client BOSH session. I need it for ios devices where background jobs are not allowed, hence long polling sessions can't be maintained for client when app is not active. When application is closed on ios device I want to keep the presence state of client 'available' and deliver push notifications. Most probably this is done already, please point me to the precedence.

Thanks.

**Comment by dhruvbird** [comment]
@netdude787 This is a problem many people face. Sorry, but I don't know a good solution to this problem though :-(

http://stackoverflow.com/questions/10459776/xmpp-push-notification-for-ios-chat-app might be helpful, but I am not aware of a spec beyond http://xmpp.org/extensions/xep-0237.html which seems to be deprecated.

You might need to "roll your own". I'd ask on the XMPP forums/SO to get a better answer though.
