### ISSUE TITLE
WebSocket only by disable BOSH service?

### ISSUE THREAD

**Issue by 2k13yr** [xmppo/node-xmpp-bosh#93]
How to configure node-xmpp-bosh to run node-xmpp-bosh via WebSocket only without BOSH service?

**Comment by dhruvbird** [comment]
Sorry, but you can't currently do that since the websocket server uses the HTTP server to upgrade to websockets. You can prevent connections to the bosh service by blocking incoming connections to the port on which bosh is listening for incoming requests.
